import { OptionsSelect } from "../Select/interfaces";
import { Column, Row } from "./interface";

export const title: Column[] = [
  { text: " ", key: "check" },
  { text: "Customer Name", key: "name" },
  { text: "Order Date", key: "date" },
  { text: "Order Type", key: "type" },
  { text: "Tracking ID", key: "track" },
  { text: "Order Total", key: "sum" },
  { text: "Action", key: "action" },
  { text: "Status", key: "status" },
];

export const options: OptionsSelect[] = [
  { value: "Completed", label: "Completed" },
  { value: "In-Progress", label: "In-Progress" },
  { value: "Pending", label: "Pending" },
  { value: "Cancel", label: "Cancel" },
];

export const row: Row[] = [
  {
    id: 1,
    name: "Janet Adebayo",
    date: "12 Aug 2022 - 12:25 am",
    type: "Home Delivery",
    track: "9348fjr73",
    sum: "22,000.00",
    action: "Completed",
    status: "Completed",
  },
  {
    id: 2,
    name: "Samuel Johnson",
    date: "12 Aug 2022 - 12:25 am",
    type: "Pick Up",
    track: "9348fjr73",
    sum: "21,000.00",
    action: "Completed",
    status: "Completed",
  },
  {
    id: 3,
    name: "Francis Doe",
    date: "12 Aug 2022 - 12:25 am",
    type: "Pick Up",
    track: "9348fjr73",
    sum: "27,000.00",
    action: "In-Progress",
    status: "In-Progress",
  },
  {
    id: 4,
    name: "Christian Dior",
    date: "12 Aug 2022 - 12:25 am",
    type: "Home Delivery",
    track: "9348fjr73",
    sum: "26,000.00",
    action: "Pending",
    status: "Pending",
  },
  {
    id: 5,
    name: "Christian Dior",
    date: "12 Aug 2022 - 12:25 am",
    type: "Home Delivery",
    track: "9348fjr73",
    sum: "26,000.00",
    action: "Pending",
    status: "Pending",
  },
  {
    id: 6,
    name: "Christian Dior",
    date: "12 Aug 2022 - 12:25 am",
    type: "Home Delivery",
    track: "9348fjr73",
    sum: "26,000.00",
    action: "Pending",
    status: "Pending",
  },
  {
    id: 7,
    name: "Christian Dior",
    date: "12 Aug 2022 - 12:25 am",
    type: "Home Delivery",
    track: "9348fjr73",
    sum: "26,000.00",
    action: "Pending",
    status: "Pending",
  },
  {
    id: 8,
    name: "Christian Dior",
    date: "12 Aug 2022 - 12:25 am",
    type: "Home Delivery",
    track: "9348fjr73",
    sum: "26,000.00",
    action: "Pending",
    status: "Pending",
  },
  {
    id: 9,
    name: "Christian Dior",
    date: "12 Aug 2022 - 12:25 am",
    type: "Home Delivery",
    track: "9348fjr73",
    sum: "26,000.00",
    action: "Pending",
    status: "Pending",
  },
  {
    id: 10,
    name: "Christian Dior",
    date: "12 Aug 2022 - 12:25 am",
    type: "Home Delivery",
    track: "9348fjr73",
    sum: "26,000.00",
    action: "Pending",
    status: "Pending",
  },
  {
    id: 11,
    name: "Christian Dior",
    date: "12 Aug 2022 - 12:25 am",
    type: "Home Delivery",
    track: "9348fjr73",
    sum: "26,000.00",
    action: "Pending",
    status: "Pending",
  },
];
